### ISSUE TITLE
CRUD endpoint for Polls

### ISSUE THREAD

**Issue by omoman** [Team-Surge/Surge-Server#1]
A poll should have the same attributes as a post, plus a list of options and their vote count. We should also be able to get polls when calling the 'list posts by self' and 'list posts' endpoints.

I'm thinking:
```json
{
    "action": "pollCreate",
    "handle": "Blah",
    "content": "Double Blah",
    "options": [
        {
            "title": "My first option title",
            "count" : 2
        },
        {
            "title":"My second option title",
            "count" : 5
        }
    ]
}
```

Polls are unique in that we need to be able to update the options vote count. Also don't know whether we want to limit users to one single vote or not (or give them the option)

@dutchthomas @Xdsxc

**Comment by dutchthomas** [comment]
Considering this:

-Limiting the poll options to 4 total options, with individual option content lengths of 50 characters max

-Poll posting will be patched into the postCreate API call

-Post will gain a "Type" attribute which must be set to either "standard" or "poll". This leaves future room for additional post types (not that we'll use them for M1). This will be sent along with postList responses in case you want to call out posts in the main view

-postDetail api call will contain the poll options, response counts, etc.

**Comment by omoman** [comment]
Sounds good to me! The UI portion should hopefully be done tonight

**Comment by dutchthomas** [comment]
Nice. I just pushed the ability to create Polls. Still need to create responses (I'm calling poll votes responses to not be ambiguous). Updating the data tab now to show polls

**Comment by dutchthomas** [comment]
Polls and responses should be complete
