### ISSUE TITLE
Location Filtering

### ISSUE THREAD

**Issue by Xdsxc** [Team-Surge/Surge-Server#2]
We still need to implement location filtering.

Requirements:
* Add support for location filtering to the database
* Add location parameter to the create post API

@dutchthomas

**Comment by dutchthomas** [comment]
Location filtering is now added to the API and has been minimally tested.

postCreate and postList must contain lat, lng properties

Please check the dev server test page for details / testing

**Comment by Xdsxc** [comment]
Working on added it now

**Comment by Xdsxc** [comment]
Adding

**Comment by Xdsxc** [comment]
Done
